#!/usr/bin/perl

sub usage
{
	die "Usage: $0 [command]\n";
}

my $cmd;
if(@ARGV == 1){
	$cmd = $ARGV[0];
}elsif(@ARGV == 0){
	$cmd = 'pbpaste';
}else{
	usage();
}

sub pbpaste
{
	return `$cmd`;
}

sub sleep_dbl
{
	select(undef, undef, undef, shift);
}

my $x = '';

while(1){
	my $y = pbpaste();

	if(!($x eq $y)){
		$x = $y;
		print "$x\n";
	}
	sleep_dbl(0.1);
}
